# Generated by Django 5.2.5 on 2025-08-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealitem',
            options={'verbose_name_plural': 'Meal food'},
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='meal',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mealitem',
            old_name='food',
            new_name='name',
        ),
    ]
