# Generated by Django 5.2.5 on 2025-08-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0002_alter_mealitem_options_rename_meal_meal_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='name',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='mealitem',
            old_name='name',
            new_name='food',
        ),
    ]
