# Generated by Django 5.2.5 on 2025-08-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0003_rename_name_meal_meal_rename_name_mealitem_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mealitem',
            old_name='food',
            new_name='name',
        ),
    ]
